<template>
  <div>
    <v-row>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Konstitution"
          type="number"
          value="3"
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Willenskraft"
          type="number"
          value="5"
        />
      </v-col>
      <v-col
        cols="12"
        sm="4"
        md="4"
      >
        <text-input
          label="Essenz"
          :rules="[rules.essence]"
          value="3.3"
        />
      </v-col>
    </v-row>
    <v-row>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Geschicklichkeit"
          type="number"
          value="3"
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Logik"
          type="number"
          value="8"
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Magie/Resonanz"
          type="number"
          value="-"
          unavailable
        />
      </v-col>
    </v-row>
    <v-row>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Reaktion"
          type="number"
          value="5"
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Intuition"
          type="number"
          value="5"
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <initiative-input
          label="Initiative"
          value="10+1d6"
        />
      </v-col>
    </v-row>
    <v-row>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Stärke"
          type="number"
          value="2"
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Charisma"
          type="number"
          value="3"
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <initiative-input
          label="Matrix-Initiative"
          value="12+1d6"
        />
      </v-col>
    </v-row>
    <v-row>
      <v-col
        cols="12"
        sm="4"
        md="4"
      >
        <text-input
          label="Edge"
          type="number"
          value="5"
        />
      </v-col>
      <v-col
        cols="12"
        sm="12"
        md="4"
      >
        <v-slider
          step="1"
          ticks="always"
          tick-size="4"
          min="0"
          max="7"
          value="5"
          dense
          hide-details
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <initiative-input
          label="Astrale Initiative"
          unavailable
        />
      </v-col>
    </v-row>
    <v-row>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Selbstbeherrschung"
          type="number"
          value="8"
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Menschenkenntnis"
          type="number"
          value="10"
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <text-input
          label="Erinnerungsvermögen"
          type="number"
          value="13"
        />
      </v-col>
    </v-row>
    <v-row>
      <v-col
        cols="12"
        sm="6"
        md="6"
      >
        <text-input
          label="Heben/Tragen"
          type="number"
          value="8"
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="6"
      >
        <text-input
          label="Bewegung"
          value="10"
        />
      </v-col>
    </v-row>
  </div>
</template>
<style lang="scss">

</style>
<script lang="ts">
import Vue from 'vue';
import TextInput from '@/components/TextInput.vue';
import InitiativeInput from '@/components/InitiativeInput.vue';

const AttributesBoxProps = Vue.extend({
  components: { InitiativeInput, TextInput },
});

export default class AttributesBox extends AttributesBoxProps {
  static label = 'Attribute';

  rules = {
    essence: (value: string) => /^\d([\\.,]\d{1,2})?$/.test(value) || 'Ungültiger Wert',
  }
}


</script>
